ivanov/compvision/box/urls.py
from django.conf.urls import patterns, url
from box import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^search/$', views.search, name="search"),
                       url(r'^results/$', views.results, name="results"),
                       )

ivanov/compvision/compvision/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'compvision.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('box.urls', namespace='box')),
)

ivanov/compvision/box/models.py
from django.db import models

# Create your models here.

class Query(models.Model):
    search_text = models.CharField(max_length=128)   
    search_date = models.DateTimeField("date_search") 

    def __unicode__(self):
        return self.search_text

class Url(models.Model):
    query = models.ForeignKey(Query)
    url = models.URLField()

    def __unicode__(self):
        return self.url

ivanov/compvision/box/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.utils import timezone

from box.models import Query, Url

import json, os, time, random
from frontend.yandex_search import get_urls
from frontend.gr import retrieveImages
from fifos.MatlabWrapper import mcmd, MatlabWrapper

INPUTNAME = '/home/ivanov/studies/django_projects/compvision/backend/input.txt'
INPUT_LOCK = '/home/ivanov/studies/django_projects/compvision/backend/input.lock'
OUTPUTNAME = '/home/ivanov/studies/django_projects/compvision/backend/output.txt'
OUTPUT_LOCK = '/home/ivanov/studies/django_projects/compvision/backend/output.lock'

# Create your views here.

def index(req):
    return render(req, 'box/index.html', {})

def search(req):
    text = req.POST['box']
    method = req.POST['methods']
    if text: 
        q = Query(search_text=text, search_date=timezone.now())
        q.save() # save to database

        url_lst = get_urls(text.encode('utf-8')) # retrieve urls from yandex
        for u in url_lst:
            q.url_set.create(url=u)
        
#        print 'Start of debugging'
        ########## debugging: delete after ###########
#        url_lst = []
#        print 'Before'
#        folders = random.sample(range(1,101), 8)
#        for folder in folders:
#            print folder
#            filename_folder = os.path.join('/mnt/Images/', str(folder))
#            filename = os.listdir(filename_folder)[0]
#            url_lst.append(os.path.join(filename_folder, filename))
        ########## end of debugging: delete before ##########
#        print 'End of debugging'

        # method 3 is not working yet
        if method == 3:
            method = 2
            
        # wait until there is no communication between Python and Matlab
        while True:
            if not os.path.exists(INPUTNAME) and not os.path.exists(INPUT_LOCK):
                with open(INPUTNAME, 'w') as f:
                    f.write(str(method) + os.linesep)
                    for u in url_lst:
                        f.write(u + os.linesep)
                open(INPUT_LOCK, 'a').close() # create input lock
                break
            time.sleep(0.1)
        print 'Created files for Matlab'
        # wait until Matlab outputs OUTPUT_LOCK
        while True:
            if os.path.exists(OUTPUT_LOCK):
                with open(OUTPUTNAME) as f:
                    pic_lst = [pic for pic in f]
                break
            time.sleep(0.1)
        # delete all files for the next process
        os.remove(OUTPUTNAME)
        os.remove(OUTPUT_LOCK)
        os.remove(INPUTNAME)
				
        # passing parameters to another view results through session
        # solution found here http://stackoverflow.com/a/8931063/2069858
        req.session['text'] = text
        req.session['url_lst'] = url_lst
        req.session['pic_lst'] = pic_lst
        req.session['method'] = method
        return redirect(reverse('box:results'))
    else:
        return render(req, 'box/index.html', {'error_message':
                                              'Please, specify a query'})

def results(req):
    text = req.session.get('text', '')
    url_lst = req.session.get('url_lst', [])
    method = req.session.get('method')
    pic_lst = req.session.get('pic_lst')
    if method == '1':
        top_pics = (pic_lst[8*i:8*(i+1)] for i in range(9))
        return render(req, 'box/1.html', {'query': text,
                                                'url_pic': zip(url_lst, *top_pics),
                                                'method': method,
                                                'range': range(len(url_lst))})
    elif method == '2':
        return render(req, 'box/2.html', {'query': text,
                                                'url': url_lst[0],
                                                'retrieved': pic_lst,
                                                'method': method,
                                                'range': range(len(url_lst))})
    elif method == '3':
        return render(req, 'box/2.html', {'query': text,
                                                'url': url_lst[0],
                                                'retrieved': pic_lst,
                                                'method': method,
                                                'range': range(len(url_lst))})
#        return render(req, 'box/3.html', {'query': text,
#                                            'url_pic': zip(url_lst, pic_lst),
#                                            'method': method,
#                                            'range' : range(len(url_lst))})
    elif method == '4':
        return render(req, 'box/4.html', {'query': text,
                                                'url_pic': zip(url_lst, pic_lst),
                                                'method': method,
                                                'range': range(len(url_lst))})
        
    

ivanov/compvision/box/templates/box/1.html
<style>
    #results {
        width: 200;
        height: 200;
    }
</style>

<a href='/'><img src="/mnt/static/box_logo.jpg" alt="Box Image"/></a>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'box:search' %}" method="post">
{% csrf_token %}
	<input type="text" name="box" id="box" size="40" value="{{ query }}" />
	<input type="submit" value="Search" />
	<br><br>You want to use:<br><br>
	<input type="radio" name="methods" value="1" {% if method == "1" %} checked {% endif %}>
	Similarity Search (PQ+PCA+VLAD)<br>
	<input type="radio" name="methods" value="2" {% if method == "2" %} checked {% endif %}>
	Duplicate Search (Min Hash)<br>
	<input type="radio" name="methods" value="3" {% if method == "3" %} checked {% endif %}>
	Improved Similarity Search (Exact Nearest Neighbor)<br>
	<input type="radio" name="methods" value="4" {% if method == "4" %} checked {% endif %}>
	Face Identification (Fisher Vectors)<br>
</form>

<h1 id="prompt">You search for <i>{{ query }}</i></h1>
<br>
<span width="100" style="position: absolute; left: 75">Yandex</span>
<span width="100" style="position: absolute; left: 275">Best 8</span>
<span width="100" style="position: absolute; left: 475">TOP1</span>
<span width="100" style="position: absolute; left: 675">TOP2</span>
<span width="100" style="position: absolute; left: 875">TOP3</span>
<span width="100" style="position: absolute; left: 1075">TOP4</span>
<span width="100" style="position: absolute; left: 1275">TOP5</span>
<span width="100" style="position: absolute; left: 1475">TOP6</span>
<span width="100" style="position: absolute; left: 1675">TOP7</span>
<span width="100" style="position: absolute; left: 1875">TOP8</span><br>
{% for url, top, top1, top2, top3, top4, top5, top6, top7, top8 in url_pic %}
	<img id="results" src="{{url}}" alt="My Image" />
    <img id="results" src="{{top}}" alt="My Image" />
    <img id="results" src="{{top1}}" alt="My Image" />
    <img id="results" src="{{top2}}" alt="My Image" />
    <img id="results" src="{{top3}}" alt="My Image" />
    <img id="results" src="{{top4}}" alt="My Image" />
    <img id="results" src="{{top5}}" alt="My Image" />
    <img id="results" src="{{top6}}" alt="My Image" />
    <img id="results" src="{{top7}}" alt="My Image" />
    <img id="results" src="{{top8}}" alt="My Image" />
	<br>
{% endfor %}

ivanov/compvision/box/templates/box/2.html
<style>
    .results {
        width: 200;
        height: 200;
    }
</style>

<a href='/'><img src="/mnt/static/box_logo.jpg" alt="Box Image"/></a>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'box:search' %}" method="post">
{% csrf_token %}
	<input type="text" name="box" id="box" size="40" value="{{ query }}" />
	<input type="submit" value="Search" />
	<br><br>You want to use:<br><br>
	<input type="radio" name="methods" value="1" {% if method == "1" %} checked {% endif %}>
	Similarity Search (PQ+PCA+VLAD)<br>
	<input type="radio" name="methods" value="2" {% if method == "2" %} checked {% endif %}>
	Duplicate Search (Min Hash)<br>
	<input type="radio" name="methods" value="3" {% if method == "3" %} checked {% endif %}>
	Improved Similarity Search (Exact Nearest Neighbor)<br>
	<input type="radio" name="methods" value="4" {% if method == "4" %} checked {% endif %}>
	Face Identification (Fisher Vectors)<br>
</form>

<h1 id="prompt">You search for <i>{{ query }}</i></h1>
<br>
<img class="results" src={{url}} alt="Yandex image" />Yandex<br>
{% for pic in retrieved %}
	<img class="results" src="{{pic}}" alt="Duplicate" />TOP{{forloop.counter}}
	<br>
{% endfor %}

ivanov/compvision/box/templates/box/3.html
<style>
    #results {
        width: 200;
        height: 200;
    }
</style>

<a href='/'><img src="/mnt/static/box_logo.jpg" alt="Box Image"/></a>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'box:search' %}" method="post">
{% csrf_token %}
	<input type="text" name="box" id="box" size="40" value="{{ query }}" />
	<input type="submit" value="Search" />
	<br><br>You want to use:<br><br>
	<input type="radio" name="methods" value="1" {% if method == "1" %} checked {% endif %}>
	Similarity Search (PQ+PCA+VLAD)<br>
	<input type="radio" name="methods" value="2" {% if method == "2" %} checked {% endif %}>
	Duplicate Search (Min Hash)<br>
	<input type="radio" name="methods" value="3" {% if method == "3" %} checked {% endif %}>
	Improved Similarity Search (Exact Nearest Neighbor)<br>
	<input type="radio" name="methods" value="4" {% if method == "4" %} checked {% endif %}>
	Face Identification (Fisher Vectors)<br>
</form>

<h1 id="prompt">You search for <i>{{ query }}</i></h1>
<br>
<span width="100" style="position: absolute; left: 75">Yandex</span>
<span width="100" style="position: absolute; left: 75">BEST8</span><br>
{% for url, pic in url_pic %}
    <img id="results" src="{{url}}" alt="URL" />
	<img id="results" src="{{pic}}" alt="Duplicate" />
	<br>
{% endfor %}

ivanov/compvision/box/templates/box/4.html
<style>
    #results {
        width: 200;
        height: 200;
    }
</style>

<a href='/'><img src="/mnt/static/box_logo.jpg" alt="Box Image"/></a>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'box:search' %}" method="post">
{% csrf_token %}
	<input type="text" name="box" id="box" size="40" value="{{ query }}" />
	<input type="submit" value="Search" />
	<br><br>You want to use:<br><br>
	<input type="radio" name="methods" value="1" {% if method == "1" %} checked {% endif %}>
	Similarity Search (PQ+PCA+VLAD)<br>
	<input type="radio" name="methods" value="2" {% if method == "2" %} checked {% endif %}>
	Duplicate Search (Min Hash)<br>
	<input type="radio" name="methods" value="3" {% if method == "3" %} checked {% endif %}>
	Improved Similarity Search (Exact Nearest Neighbor)<br>
	<input type="radio" name="methods" value="4" {% if method == "4" %} checked {% endif %}>
	Face Identification (Fisher Vectors)<br>
</form>

<h1 id="prompt">You search for <i>{{ query }}</i></h1>
<br>
<span width="100" style="position: absolute; left: 75">Yandex</span>
<span width="100" style="position: absolute; left: 275">Best 8</span><br>
{% for url, top in url_pic %}
	<img id="results" src="{{url}}" alt="My Image" />
    <img id="results" src="{{top}}" alt="My Image" />
	<br>
{% endfor %}

ivanov/compvision/box/templates/box/index.html
<style>
    h4 {
        font-size: 5em;
        }
    h5 {
        font-size: 2em;
        color: #7E807F;
        }
        
    form {
    }
    .layout {
        padding-left: 30%;
        padding-top: 10%;
    }
</style>
<div class="layout">
    <h4 style="color:green"><span style="color:red;">B</span>o<span style="color:blue">x</span></h1>
    <h5>Search in million of images</h2> 

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'box:search' %}" method="post">
    {% csrf_token %}
	    <input type="text" name="box" id="box" size="50" value="" />
	    <input type="submit" value="Search" />
	    <br><br>You want to use:<br><br>
	    <input type="radio" name="methods" value="1" checked>Similarity Search (PQ+PCA+VLAD)<br>
	    <input type="radio" name="methods" value="2">Duplicate Search (Min Hash)<br>
	    <input type="radio" name="methods" value="3">Improved Similarity Search (Exact Nearest Neighbor)<br>
	    <input type="radio" name="methods" value="4">Face Identification (Fisher Vectors)<br>
	
    </form>
</div>